spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: temporal-worker
server:
  port: 8080
worker:
  temporal:
    target: ${TEMPORAL_ADDRESS}
services:
  inventory: ${INVENTORY_SERVICE_URL:http://localhost:8080}
  payment: ${PAYMENT_SERVICE_URL:http://localhost:8080}
  orders: ${ORDER_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
