server:
  port: 8080

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.abhishek.limitedcart.common.events"
#        spring.json.value.default.type: "com.abhishek.limitedcart.common.events.OrderProgressEvent"

app:
  kafka:
    topics:
      orderProgress: ${KAFKA_TOPIC_ORDER_PROGRESS:order.progress}
  security:
    allowed-origins: ${ALLOWED_HOST_CORS:http://localhost:3000}
    jwt:
      secret: ${JWT_SECRET}
      issuer: limitedcart-auth
      expiration-seconds: ${JWT_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
