apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: limitedcart
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP: "kafka-service:9092"
  TEMPORAL_ADDRESS: "temporal-service:7233"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  ZIPKIN_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
  ALLOWED_HOST_CORS: "http://localhost:63342,http://localhost:8080,http://localhost"
  PAYMENT_PROVIDER_MODE: "mock"
  PAYMENT_FRONTEND_BASE_URL: "http://localhost" # Ingress will handle this
  ORDER_SERVICE_URL: "http://order-service:8080"
  INVENTORY_SERVICE_URL: "http://inventory-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
  # DB Names
  AUTH_DB: "auth_db"
  PRODUCT_DB: "product_db"
  INVENTORY_DB: "inventory_db"
  ORDERS_DB: "orders_db"
  PAYMENT_DB: "payment_db"
