apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: limitedcart
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASSWORD: "12345678"
  JWT_SECRET: "7cdd1515152b814ebe9b2d0b4fddcf23055fa6ab91682dde4a839199de4e0e0f"
  JWT_EXPIRATION: "604800"
  ADMIN_BOOTSTRAP_EMAIL: "a@g.com"
  ADMIN_BOOTSTRAP_PASSWORD: "12345678"
