name: frontend_web
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State Management
  provider: ^6.0.5

  # Routing
  go_router: ^12.0.0

  # Networking
  dio: ^5.3.2

  # Storage
  shared_preferences: ^2.2.0

  # Utilities
  intl: ^0.18.1

  # Icons
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
